version: 2.1
orbs:
  android: circleci/android@2.3.0
  marathon-cloud: marathonlabs/marathon-cloud-orb@0.1.0
jobs:
  build:
    executor:
      name: android/android-docker
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: assemble
          command: ./gradlew assembleDebug assembleAndroidTest
      - android/save-gradle-cache
  test:
    executor: marathon-cloud/default
    steps:
      - marathon-cloud/run_tests:
          apiKey: $MARATHON_CLOUD_API_TOKEN
          application: android-app/app/build/outputs/apk/debug/app-debug.apk
          testApplication: android-app/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
workflows:
  testing-workflow:
    jobs:
      - build
      - test
